### ISSUE TITLE
Flux capacitor monitor

### ISSUE THREAD

**Issue by RussBarton-NOAA** [NOAA-OWP/gh-train#7]
Please add a monitor for the flux capacitor.

**Comment by aaraney** [comment]
@RussBarton-NOAA, I hope this will do...
![back to the future dash gauge](https://static.wikia.nocookie.net/bttf/images/6/6b/Roentgen_meter.jpg/revision/latest?cb=20070218061029)

**Comment by RussBarton-NOAA** [comment]
Perfect.
